// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/interface_repository.go

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	models "github.com/KennyKur/CRUD_Todo/models"
	gomock "github.com/golang/mock/gomock"
)

// MockTodoRepositoryInterface is a mock of TodoRepositoryInterface interface.
type MockTodoRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTodoRepositoryInterfaceMockRecorder
}

// MockTodoRepositoryInterfaceMockRecorder is the mock recorder for MockTodoRepositoryInterface.
type MockTodoRepositoryInterfaceMockRecorder struct {
	mock *MockTodoRepositoryInterface
}

// NewMockTodoRepositoryInterface creates a new mock instance.
func NewMockTodoRepositoryInterface(ctrl *gomock.Controller) *MockTodoRepositoryInterface {
	mock := &MockTodoRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTodoRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoRepositoryInterface) EXPECT() *MockTodoRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTodoRepositoryInterface) Create(ctx context.Context, todo models.User_todo_list) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, todo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTodoRepositoryInterfaceMockRecorder) Create(ctx, todo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTodoRepositoryInterface)(nil).Create), ctx, todo)
}

// Delete mocks base method.
func (m *MockTodoRepositoryInterface) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTodoRepositoryInterfaceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTodoRepositoryInterface)(nil).Delete), ctx, id)
}

// Fetch mocks base method.
func (m *MockTodoRepositoryInterface) Fetch(ctx context.Context) ([]models.User_todo_list, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx)
	ret0, _ := ret[0].([]models.User_todo_list)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockTodoRepositoryInterfaceMockRecorder) Fetch(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockTodoRepositoryInterface)(nil).Fetch), ctx)
}

// GetByID mocks base method.
func (m *MockTodoRepositoryInterface) GetByID(ctx context.Context, id int64) (models.User_todo_list, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.User_todo_list)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTodoRepositoryInterfaceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTodoRepositoryInterface)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockTodoRepositoryInterface) Update(ctx context.Context, todo models.User_todo_list, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, todo, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTodoRepositoryInterfaceMockRecorder) Update(ctx, todo, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTodoRepositoryInterface)(nil).Update), ctx, todo, id)
}
